name: Build Pico-ASHA UF2

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib python3 pkg-config
        
    - name: Clone and setup Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init
        
        # Export PICO_SDK_PATH environment variable for the build process
        echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV
        
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure CMake
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DPICO_SDK_PATH=$PICO_SDK_PATH ..
      
    - name: Build project
      run: |
        cd build
        make -j4
        
    - name: List build artifacts
      run: find build -name "*.uf2" -o -name "*.bin" -o -name "*.elf"
      
    - name: Upload UF2 file
      uses: actions/upload-artifact@v3
      with:
        name: pico-asha-firmware
        path: |
          build/*.uf2
          build/src/*.uf2
        if-no-files-found: error
        
    - name: Upload ELF file (for debugging)
      uses: actions/upload-artifact@v3
      with:
        name: pico-asha-debug
        path: |
          build/*.elf
          build/src/*.elf
        if-no-files-found: warn 